### ISSUE TITLE
Testing Result Template

### ISSUE THREAD

**Issue by sifnoc** [zkopru-network/stress-test#3]
I wrote a simple stats page for stress testing results.

@wanseob @JChanceHud Any suggestions on what metrics should be added here?

# Zkopru Stress Test - 1
### Testing
 PR / Commit : [#225](https://github.com/zkopru-network/zkopru/pull/225) / [c9f0908](https://github.com/sifnoc/zkopru/commit/c9f0908698680be01709e31592ef02077c7102c7)
 
 Branch : [feat/generator](https://github.com/sifnoc/zkopru/tree/feat/generator)
 
 Start DateTime : 2021-09-09 00:00:00 UTC
 
 End DateTime : 2021-09-10 00:38:23 UTC
 
 Duration : 24h 38m 23s

### Host System
 Cpu :

 Memory:

### Layer1
| Key                    | Value                    |
|------------------------|--------------------------|
| Chain ID               | 20200406                 |
| Avg Block Gas Limit    | 12000000                 |
| Avg Gas Price(Wei)     | 1                        |
| Node                   | Ganache / Hardhat / Geth |

### Zkopru Contract
| Name                  | Value   |
|-----------------------|---------|
| Max Block Size        | 200000  |
| Max Validation Gas    | 6000000 |
| Challenge Period      | 26523   |
| Minimum Stake (Ether) | 32      |
| Max Utxo              | 65536   |

### Coordinators
| Name          | Address     | Max Bytes | Price Multiplier | Max Bid |
|---------------|-------------|-----------|------------------|---------|
| coordinator_1 | 0x123456789 | 131072    | 48               | 2000    |
| coordinator_2 | 0x23456789A | 131072    | 48               | 1000    |

### Performances
| Keys               | Value      |
|--------------------|------------|
| Average TPS        | 15.3 tx/s  |
| Average Fee per Tx | 1,000,000  |
| Last 24 Hours TPS  | 10.12 tx/s |
| Las 1 Hour TPS     | 8.8 tx/s   |

### Coordinators
| Name          | Address     | Proposed | Processed Tx Count | Total Spent for Bid | Total Earn Fee |
|---------------|-------------|----------|--------------------|---------------------|----------------|
| coordinator_1 | 0x123456789 | 12       | 120                |                     |                |
| coordinator_2 | 0x23456789A | 0        | 0                  |                     |                |

### Wallets
| Name     | Address     | Generated Tx | Total Spent Fee (wei) |
|----------|-------------|--------------|-----------------------|
| wallet_1 | 0x012345678 | 128          | 1280000               |
| wallet_2 | 0x023456789 | 21           | 210000                |

### Layer1 Blocks
| Block Number | Txs | Zkopru Related Txs* | Block Hashes |
|--------------|-----|---------------------|--------------|
| 230          | 12  | 1                   | 0xdead       |
| 247          | 12  | 2                   | 0xdead       |
| 249          | 14  | 1                   | 0xdead       |
| 260          | 16  | 2                   | 0xdead       |
* Only show blocks data which included tx from stress-test participant.

### Zkopru Blocks
| Propose Number | Duration | Included Transactions | Block Hashes | Layer1 Tx Hash | Proposer      |
|----------------|----------|-----------------------|--------------|----------------|---------------|
| 1              | 10       | 1                     | deaddead       | 0x000000000001 | coordinator_1 |
| 2              | 12       | 2                     | deaddead       | 0x000000000002 | coordinator_1 |
| 3              | 14       | 4                     | deaddead       | 0x000000000003 | coordinator_1 |
| 4              | 16       | 8                     | deaddead       | 0x000000000004 | coordinator_1 |

### Auction Data
| Propose Number | Highest Bidder | Highest Bid Amount | Total Bid Counts |
|----------------|----------------|--------------------|------------------|
| 1              | 0x123456789a   | 2000000000         | 2                |
| 2              | 0x123456789a   | 2000000000         | 2                |
| 3              | 0x123456789a   | 2000000000         | 2                |

**Comment by wanseob** [comment]
looks very good to me!

**Comment by sifnoc** [comment]
Sample page on serv on vercel

https://stress-test-results-hcvs75e1p-zkopru.vercel.app/
